version: '3'
services:
  
  #PHP Service
  app:
    build:
      context: ./code
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    volumes:
      - ./code:${PROJECT_PATH}
      - ./build/php/conf.d/local/ini:/usr/local/etc/php/conf.d/local.ini
      - ./build/php/php-fpm.d/www2.conf:/usr/local/etc/php-fpm.d/www2.conf

    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: ${PROJECT_PATH}
    networks:
      local:
        aliases:
          - ${NETWORK}


  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - ./code:${PROJECT_PATH}
      - ./build/nginx/conf.d/:/etc/nginx/conf.d/
      #- ./build/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./build/nginx/log:/var/log/nginx
    depends_on:
      - app

    networks:
      local:
        aliases:
          - ${NETWORK}

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: P@ssw0rd12#
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./data/dbdata:/var/lib/mysql
      - ./build/mysql/mysql.conf.d/mysql.cnf:/etc/mysql/mysql.conf.d/mysql.cnf
    networks:
      local:
        aliases:
          - ${NETWORK}

#Docker Networks
networks:
  local:
    name: ${NETWORK}
